name = "launcherfiles"
main = "index.js"
compatibility_date = "2026-02-08"

[[r2_buckets]]
binding = "FILES_BUCKET"      # must match the variable in index.js
bucket_name = "myfiles"       # your R2 bucket name
preview_bucket_name = "myfiles"
